# Generated by Django 4.2.6 on 2023-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("available_weight", models.FloatField()),
                ("price_per_kg", models.FloatField()),
            ],
        ),
    ]
